# Generated by Django 3.1.1 on 2020-10-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0006_favouritetags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritetags',
            name='tag_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='like_tag', to='taggit.tag'),
        ),
    ]
