# Generated by Django 3.1.1 on 2020-10-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_savedposts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedPosts',
        ),
    ]
